name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - env: 
        CORE_DART_HOST_URL: ${{ secrets.CORE_DART_HOST_URL }}
        CORE_DART_PRIMARY_USER: ${{ secrets.CORE_DART_PRIMARY_USER }}
        CORE_DART_PRIMARY_USER_NAME: ${{ secrets.CORE_DART_PRIMARY_USER_NAME }}
        CORE_DART_PRIMARY_USER_EMAIL: ${{ secrets.CORE_DART_PRIMARY_USER_EMAIL }}
        CORE_DART_PRIMARY_USER_PWD: ${{ secrets.CORE_DART_PRIMARY_USER_PWD }}
        CORE_DART_SECONDARY_USER: ${{ secrets.CORE_DART_SECONDARY_USER }}
        CORE_DART_SECONDARY_USER_PWD: ${{ secrets.CORE_DART_SECONDARY_USER_PWD }}
        CORE_DART_MOBILE_NUMBER: ${{ secrets.CORE_DART_MOBILE_NUMBER }}
        CORE_DART_PIN_NUMBER: ${{ secrets.CORE_DART_PIN_NUMBER }}
        CORE_DART_EXISTING_FOLDER: ${{ secrets.CORE_DART_EXISTING_FOLDER }}
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
